/**
 * @file Required top-level nodes (DOCUMENT, CANVAS, Internal Only Canvas).
 *
 * Every importable Figma file contains:
 * - exactly one DOCUMENT root,
 * - at least one user-visible CANVAS,
 * - one CANVAS marked `internalOnly: true` (real Figma exports also
 *   set `visible: false` and name it "Internal Only Canvas" — see
 *   `docs/refactor/component-type-cleanup.md` for the disk SoT;
 *   `internalOnly: true` is the load-bearing flag that hides the
 *   canvas from the Pages UI, the rest is decorative).
 *
 * The Internal Only canvas hosts internal scratch state Figma uses
 * during import; without it, files generated by older builders fail
 * silently in the Figma desktop app.
 */

import type { FigNode } from "@higma-document-models/fig/types";
import type { LintRule } from "../types";

function getTypeName(node: FigNode): string {
  return node.type?.name ?? "UNKNOWN";
}

function isInternalOnlyCanvas(node: FigNode): boolean {
  if (getTypeName(node) !== "CANVAS") {
    return false;
  }
  if (node.name === "Internal Only Canvas") {
    return true;
  }
  return Boolean((node as { internalOnly?: boolean }).internalOnly);
}

export const requiredNodesRule: LintRule = (ctx, emit) => {
  if (ctx.nodeChanges.length === 0) {
    return;
  }
  const documents = ctx.nodeChanges.filter((node) => getTypeName(node) === "DOCUMENT");
  if (documents.length === 0) {
    emit({
      ruleId: "fig.message.required-roots",
      severity: "error",
      path: "nodeChanges",
      message: "No DOCUMENT node found — every fig file needs exactly one DOCUMENT root",
      remediation: "Call `createEmptyFigDocument(name)` before adding canvases",
    });
  }
  if (documents.length > 1) {
    emit({
      ruleId: "fig.message.required-roots",
      severity: "error",
      path: "nodeChanges",
      message: `Found ${documents.length} DOCUMENT nodes — exactly one is required`,
      remediation: "Remove duplicate DOCUMENT entries from the nodeChanges stream",
    });
  }

  const canvases = ctx.nodeChanges.filter((node) => getTypeName(node) === "CANVAS");
  const userCanvases = canvases.filter((node) => !isInternalOnlyCanvas(node));
  const internalCanvases = canvases.filter((node) => isInternalOnlyCanvas(node));

  if (userCanvases.length === 0) {
    emit({
      ruleId: "fig.message.required-roots",
      severity: "error",
      path: "nodeChanges",
      message: "No user-visible CANVAS found — Figma cannot render an empty document",
      remediation: "Add at least one CANVAS with `addPage({state, doc, name})`",
    });
  }

  if (internalCanvases.length === 0) {
    emit({
      ruleId: "fig.canvas.internal-only",
      severity: "error",
      path: "nodeChanges",
      message: "Missing Internal Only Canvas — Figma's importer requires this hidden canvas",
      remediation: "Call `addPage({state, doc, name, internalOnly: true})` when generating fixtures",
    });
  }
};
