/** @file Scene graph builder / diff / render barrel. */

export * from "./model";

// Builder
export {
  buildSceneGraph,
  buildSceneGraphWithCache,
  type BuildSceneGraphOptions,
  type BuildSceneGraphResult,
  type SceneGraphBuildCache,
} from "./builder";

export {
  readSceneGraphNodeChildren,
  replaceSceneGraphNodeChildren,
  sceneGraphNodeOwnsChildren,
  type SceneGraphNodeWithChildren,
} from "./scene-graph-node-children";

export {
  createKiwiSceneGraphPipeline,
  type KiwiSceneGraphMutation,
  type KiwiSceneGraphMutationScope,
  type KiwiSceneGraphPipeline,
  type KiwiSceneGraphPipelineInput,
} from "./kiwi-scene-graph-pipeline";

export {
  findSceneGraphNode,
  replaceSceneGraphNodeTransform,
  translateSceneGraphNode,
  translateSceneNodeTransform,
  type SceneGraphNodeTranslation,
} from "./translate-scene-node";

export {
  flattenSceneGraphNodeBounds,
  translateSceneGraphNodeBounds,
  type SceneGraphBoundsLike,
  type SceneGraphNodeBounds,
} from "./node-bounds";

// Render — shared SoT for SceneGraph → SVG attribute resolution
// Both SVG string and React renderers MUST consume these exclusively.
export {
  colorToHex,
  uint8ArrayToBase64,
  resolveBrowserRenderedFigmaExportCssBlendMode,
  resolveFill,
  resolveFillWithRenderSettings,
  resolveTopFill,
  resolveTopFillWithRenderSettings,
  resolveStroke,
  resolveStrokeResult,
  resolveEffects,
  resolveEffectBounds,
  resolveBrowserRenderedFigmaExportEffectBlendMode,
  resolveFigmaBlurStdDeviation,
  buildEffectStack,
  buildLayerBlurCapturedContentEffectStack,
  renderShapeEffectStack,
  resolveFrameSurfaceFilterEffects,
  finalizeGradientDefs,
  finalizeImagePatternDefs,
  finalizeImagePatternDefsWithRenderSettings,
  resolveFigmaRenderExportSettings,
  resolveSvgMaskElementAttrs,
  resolveSvgMaskPresentation,
  resolveSvgStrokeMaskElementAttrs,
  clampSvgRectCornerRadius,
  resolveLayeredRectShapePrimitive,
  resolvePathBackedRectShapePrimitive,
  resolvePathContourRectPrimitive,
  resolveRectShapePrimitive,
  renderExportSettingsCacheKey,
  requireManagedImageColorProfile,
  type ResolvedFill,
  type ResolvedFillAttrs,
  type ResolvedFillDef,
  type ResolvedGradientStop,
  type ResolvedLinearGradient,
  type ResolvedRadialGradient,
  type ResolvedAngularGradient,
  type ResolvedDiamondGradient,
  type ResolvedImagePattern,
  type ResolvedStrokeAttrs,
  type ResolvedStrokeLayer,
  type ResolvedStrokeResult,
  type ResolvedFilter,
  type ResolvedFilterPrimitive,
  type FrameSurfaceFilterEffect,
  type ResolvedEffectStack,
  type ShapeEffectStackParams,
  type ElementSize,
  type FigmaImageResamplingSettings,
  type FigmaPdfImageQuality,
  type FigmaRenderExportSettings,
  type RenderExportSettingsCacheKey,
  type ResolvedFigmaRenderExportSettings,
  type SvgMaskElementAttrs,
  type SvgMaskPresentation,
  type SvgMaskType,
  type SvgStrokeMaskElementAttrs,
  type IdGenerator,
  type SceneGraphRenderOptions,
  type BrowserRenderedFigmaExportCssBlendMode,
  type PathContourRectSize,
  type RectShapePrimitive,
} from "./render";

// RenderTree — intermediate representation for SVG/React/WebGL backends
export {
  resolveRenderTree,
  resolveRenderTreeWithReferenceReuse,
  boundsIntersect,
  boundsUnion,
  canRenderContainerOpacityWithInheritedOpacity,
  canSkipFrameChildClipBecauseChildVisualSubtreesCannotReachClipBoundary,
  getClipShapeLocalBounds,
  getRenderFrameLocalSurfaceFilterInputBounds,
  getRenderNodeLocalAuthoredBounds,
  getRenderNodeLocalBounds,
  getRenderNodeLocalFrameChildClipBounds,
  RENDER_NODE_SOURCE_TRANSFORMS,
  renderNodeIntersectsViewport,
  resolveRenderNodeLocalSourceEffectInputBounds,
  resolveRenderNodeLocalSubtreeVisualBounds,
  resolveRenderNodeOutputBoundsAffectedByTranslatedNode,
  transformBounds,
  type RenderTree,
  type RenderTreeReferenceReuseState,
  type RenderTreeReferenceReuseResult,
  type RenderNode,
  type RenderNodeBase,
  type RenderGroupNode,
  type RenderFrameNode,
  type RenderFrameBackground,
  type RenderFrameSurfaceShape,
  type RenderRectNode,
  type RenderEllipseNode,
  type RenderPathNode,
  type RenderPathContour,
  type RenderTextNode,
  type RenderTextGlyphs,
  type RenderTextLines,
  type RenderImageNode,
  type RenderDef,
  type RenderGradientDef,
  type RenderLinearGradientDef,
  type RenderRadialGradientDef,
  type RenderAngularGradientDef,
  type RenderDiamondGradientDef,
  type RenderFilterDef,
  type RenderClipPathDef,
  type RenderPatternDef,
  type RenderMaskDef,
  type RenderMaskContentRendering,
  type RenderStrokeMaskDef,
  type RenderMask,
  type ClipPathShape,
  type ResolvedWrapperAttrs,
  type ResolvedFillResult,
  type ResolvedFillLayer,
  type RenderBackgroundBlur,
  type StrokeRendering,
  type StrokeShape,
  type RenderTextGlyphRun,
  type Bounds,
  type RenderNodeTranslatedOutputBounds,
  type RenderNodeVisualTransform,
  type ViewportIntersectionOptions,
  type ViewportRect,
} from "./render-tree";

// Converters
export {
  figColorToSceneColor,
  convertPaintToFill,
  convertPaintsToFills,
  convertStrokeToSceneStroke,
  convertEffectsToScene,
  decodeGeometryToContours,
  convertVectorPathsToContours,
  convertTextNode,
  type TextConversionResult,
} from "./convert";
