/**
 * @file FRAME decoration preservation tests
 *
 * Verifies that FRAME-level properties (background fill, stroke, effects,
 * corner radius, opacity) survive the full pipeline:
 * parseFigFile → buildNodeTree → renderCanvas → SVG string.
 *
 * The fixture frame-properties.fig is generated by
 * scripts/generate-frame-properties-fixtures.ts and contains every
 * commonly missed decoration combination on a FRAME.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import pixelmatch from "pixelmatch";
import { readPng, createPngImage } from "@higuma/png";
import {
  parseFigFile,
  buildNodeTree,
  findNodesByType,
} from "@higuma/fig/parser";
import type { FigNode } from "@higuma/fig/types";
import { renderCanvas } from "../src/svg/renderer";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(__dirname, "../fixtures/frame-properties");
const FIG_FILE = path.join(FIXTURES_DIR, "frame-properties.fig");
const ACTUAL_DIR = path.join(FIXTURES_DIR, "actual");

type FrameFixture = {
  readonly name: string;
  readonly node: FigNode;
  readonly size: { readonly width: number; readonly height: number };
};

type ParsedFixture = {
  readonly frames: ReadonlyMap<string, FrameFixture>;
  readonly blobs: Parameters<typeof renderCanvas>[1]["blobs"];
  readonly images: Parameters<typeof renderCanvas>[1]["images"];
  readonly nodeMap: Parameters<typeof renderCanvas>[1]["symbolMap"];
};

async function loadFixture(): Promise<ParsedFixture> {
  if (!fs.existsSync(FIG_FILE)) {
    throw new Error(
      `Fixture file not found: ${FIG_FILE}\n` +
      `Run: bun packages/@higuma/fig-renderer/scripts/generate-frame-properties-fixtures.ts`,
    );
  }
  const data = fs.readFileSync(FIG_FILE);
  const parsed = await parseFigFile(new Uint8Array(data));
  const { roots, nodeMap } = buildNodeTree(parsed.nodeChanges);
  const canvases = findNodesByType(roots, "CANVAS");

  const frames = new Map<string, FrameFixture>();
  for (const canvas of canvases) {
    for (const child of canvas.children ?? []) {
      if (child.type?.name !== "FRAME") {continue;}
      const name = child.name ?? "unnamed";
      const size = child.size;
      frames.set(name, {
        name,
        node: child,
        size: { width: size?.x ?? 100, height: size?.y ?? 100 },
      });
    }
  }
  return { frames, blobs: parsed.blobs, images: parsed.images, nodeMap };
}

async function renderFrame(fixture: ParsedFixture, name: string): Promise<string> {
  const frame = fixture.frames.get(name);
  if (!frame) {
    throw new Error(`Frame "${name}" not in fixture. Available: ${[...fixture.frames.keys()].join(", ")}`);
  }
  const wrapper: FigNode = {
    type: { value: 2, name: "CANVAS" },
    name,
    children: [frame.node],
  };
  const result = await renderCanvas(wrapper, {
    width: frame.size.width,
    height: frame.size.height,
    blobs: fixture.blobs,
    images: fixture.images,
    symbolMap: fixture.nodeMap,
  });
  return result.svg;
}

// eslint-disable-next-line no-restricted-syntax -- mutable test-suite variable initialized in beforeAll
let fixture: ParsedFixture;

beforeAll(async () => {
  fixture = await loadFixture();
});

describe("FRAME decoration preservation — end-to-end through SVG", () => {
  it("loads the fixture with every named FRAME present", () => {
    const expected = [
      "frame-bg-fill",
      "frame-corner-clip",
      "frame-nested",
      "frame-child-effects",
      "frame-opacity",
      "frame-drop-shadow",
      "frame-inner-shadow",
      "frame-stroke",
      "frame-overlap",
      "frame-deep-clip",
    ];
    for (const name of expected) {
      expect(fixture.frames.has(name), `Fixture should contain FRAME "${name}"`).toBe(true);
    }
  });

  it("FRAME background fill appears in SVG output with correct colour", async () => {
    // frame-bg-fill has fill {r: 0.2, g: 0.5, b: 0.9} → expected #3380e6.
    // The half-ULP epsilon in channelToByte handles float32 precision loss
    // (0.9 → 0.8999.. * 255 = 229.4999..) so boundary values round correctly.
    const svg = await renderFrame(fixture, "frame-bg-fill");
    expect(svg).toMatch(/#3380e6|rgb\(51, ?128, ?230\)/i);
  });

  it("FRAME stroke border appears in SVG output", async () => {
    // frame-stroke: stroke {r: 0.05, g: 0.05, b: 0.05} ≈ #0d0d0d, weight 4.
    // FRAME's default strokeAlign is INSIDE → SVG renderer doubles the width
    // and masks to the inner half. So stroke-width="8" is correct behaviour
    // (documented in render/stroke.ts insideOutsideStrokeWidth).
    const svg = await renderFrame(fixture, "frame-stroke");
    expect(svg).toMatch(/stroke="#0d0d0d"|stroke="rgb\(13, ?13, ?13\)"/i);
    // Accept either unmasked width=4 or inside/outside masked width=8.
    expect(svg).toMatch(/stroke-width="(4|8)"/);
    // Stroke must be masked (INSIDE align) or drawn directly (CENTER align).
    // Either way the weight must appear.
  });

  it("FRAME corner radius appears in SVG output", async () => {
    // frame-corner-clip has cornerRadius 16 — renders as rx/ry, an arc
    // command (per-corner radii), or a cubic Bézier rounded-rect path.
    const svg = await renderFrame(fixture, "frame-corner-clip");
    const hasRx = /rx="16"/.test(svg);
    const hasArc = /A\s*16[, ]16/.test(svg);
    // Cubic Bézier: rounded-rect path passes through (16, 0) and (0, 16)
    // for a top-left corner. Match either L line or C cubic with 16 in
    // the relevant slots.
    const hasBezier = /L\s+16\s+0|L\s+0\s+16|C\s+0\s+\S+\s+\S+\s+0\s+16/.test(svg);
    expect(hasRx || hasArc || hasBezier, "Corner radius 16 must appear as rx, arc, or cubic Bézier in SVG").toBe(true);
  });

  it("FRAME drop-shadow effect appears in SVG output", async () => {
    // frame-drop-shadow has dropShadow offset(0,6) blur(12)
    const svg = await renderFrame(fixture, "frame-drop-shadow");
    // Drop shadow renders as feDropShadow or feGaussianBlur + feOffset filter.
    const hasFilter = /<feDropShadow|<feGaussianBlur/i.test(svg);
    expect(hasFilter, "Drop shadow effect must produce an SVG filter element").toBe(true);
  });

  it("FRAME inner-shadow effect appears in SVG output", async () => {
    // frame-inner-shadow
    const svg = await renderFrame(fixture, "frame-inner-shadow");
    const hasFilter = /<filter\b|<feGaussianBlur|<feOffset|<feComposite/i.test(svg);
    expect(hasFilter, "Inner shadow effect must produce an SVG filter element").toBe(true);
  });

  it("FRAME opacity appears in SVG output", async () => {
    // frame-opacity has opacity 0.5
    const svg = await renderFrame(fixture, "frame-opacity");
    expect(svg).toMatch(/opacity="0?\.5"/);
  });

  it("FRAME fill + stroke + corner radius survive together", async () => {
    // frame-stroke has fill WHITE + stroke #0d0d0d + cornerRadius 10
    const svg = await renderFrame(fixture, "frame-stroke");
    // WHITE fill (#ffffff)
    expect(svg).toMatch(/fill="#ffffff"|fill="white"|fill="rgb\(255, ?255, ?255\)"/i);
    // Stroke
    expect(svg).toMatch(/stroke="#0d0d0d"|stroke="rgb\(13, ?13, ?13\)"/i);
    // cornerRadius 10 — appears as rx/ry, A arc, or cubic Bézier rounded-rect.
    const hasRx = /rx="10"/.test(svg);
    const hasArc = /A\s*10[, ]10/.test(svg);
    const hasBezier = /L\s+10\s+0|L\s+0\s+10|C\s+0\s+\S+\s+\S+\s+0\s+10/.test(svg);
    expect(hasRx || hasArc || hasBezier, "Corner radius 10 must appear in SVG").toBe(true);
  });

  it("nested FRAMEs both render their fills", async () => {
    // frame-nested: outer fill {r: 0.95, ...}, inner fill {r: 0.9, g: 0.3, b: 0.3}.
    // With the channelToByte epsilon, 0.9 now rounds correctly to 230 (#e6).
    const svg = await renderFrame(fixture, "frame-nested");
    expect(svg).toMatch(/#e64d4d|rgb\(230, ?77, ?77\)/i);
  });
});

// =============================================================================
// Pixel-level comparison vs Figma's own SVG export
// =============================================================================

function svgToPng(svg: string, width: number): Buffer {
  const resvg = new Resvg(svg, {
    fitTo: { mode: "width", value: width },
    background: "white",
  });
  return Buffer.from(resvg.render().asPng());
}

describe("FRAME decoration pixel-parity with Figma export", () => {
  // Frames where our rendering should match Figma's SVG export to within 1%.
  // frame-stroke is intentionally excluded: Figma's SVG export writes
  // stroke-width=4 centered even when strokeAlign=INSIDE, while our renderer
  // correctly honours INSIDE via the mask-double-width trick. Our output
  // matches Figma's canvas display, not Figma's lossy SVG export.
  const frames = [
    "frame-bg-fill",
    "frame-corner-clip",
    "frame-nested",
    "frame-child-effects",
    "frame-opacity",
    "frame-drop-shadow",
    "frame-inner-shadow",
    "frame-overlap",
    "frame-deep-clip",
  ];

  for (const name of frames) {
    it(`${name}: matches Figma SVG export within 1% pixels`, async () => {
      const actualPath = path.join(ACTUAL_DIR, `${name}.svg`);
      if (!fs.existsSync(actualPath)) {
        throw new Error(`Missing Figma actual export: ${actualPath}`);
      }
      const frame = fixture.frames.get(name);
      if (!frame) {throw new Error(`Frame ${name} missing from fixture`);}
      const ourSvg = await renderFrame(fixture, name);
      const actualSvg = fs.readFileSync(actualPath, "utf-8");

      const ourPng = readPng(svgToPng(ourSvg, frame.size.width));
      const actualPng = readPng(svgToPng(actualSvg, frame.size.width));
      expect(ourPng.width).toBe(actualPng.width);
      expect(ourPng.height).toBe(actualPng.height);

      const diff = createPngImage({ width: ourPng.width, height: ourPng.height });
      const diffPx = pixelmatch(ourPng.data, actualPng.data, diff.data, ourPng.width, ourPng.height, { threshold: 0.1 });
      const totalPx = ourPng.width * ourPng.height;
      const pct = (diffPx / totalPx) * 100;
      expect(pct, `${name}: ${diffPx}/${totalPx} px differ (${pct.toFixed(2)}%)`).toBeLessThan(1);
    });
  }
});
