/**
 * @file CSS custom-property emitter.
 *
 * Layout:
 *
 *   :root {
 *     // Default mode values for every variable set + every style.
 *     --colors-primary: #0066ff;
 *     --spacing-md: 16px;
 *   }
 *
 *   :root[data-colors-mode="Dark"] {
 *     --colors-primary: #3399ff;
 *   }
 *
 * Each variable set's slug becomes its own `data-<slug>-mode` attribute,
 * so consumers can toggle them independently (a "Colors" set with
 * Light/Dark, and a "Density" set with Default/Compact, never need to
 * share a single `data-mode` attribute). Style-sourced tokens have no
 * modes — they always live in the `:root` block.
 *
 * Typography composites expand into one variable per sub-property
 * (`--id-font-family`, `-font-size`, `-font-weight`, ...) so consumers
 * can swap individual fields. The DTCG JSON emitter keeps them nested.
 */

import type { Token, TokenSet, TokenValue, TypographyValue } from "../token-set";
import { slugifyForCss } from "../extract/name";

export type TokensToCssOptions = {
  /**
   * Pre-amble comment. When `"banner"` (default), prepends a single
   * "Generated by @higma-tools/fig-to-tokens" comment. `"none"` skips
   * it so consumers can layer their own header.
   */
  readonly preamble?: "banner" | "none";
};

const GENERATED_BANNER = "/* Generated by @higma-tools/fig-to-tokens. Do not edit by hand. */";

/** Serialize `tokens` to a CSS custom-properties string. */
export function tokensToCss(tokens: TokenSet, options: TokensToCssOptions = {}): string {
  const blocks: string[] = [];
  if (options.preamble !== "none") {
    blocks.push(GENERATED_BANNER);
  }
  blocks.push(renderRootBlock(tokens));
  for (const overrideBlock of renderModeOverrideBlocks(tokens)) {
    blocks.push(overrideBlock);
  }
  return `${blocks.filter((b) => b.length > 0).join("\n\n")}\n`;
}

function renderRootBlock(tokens: TokenSet): string {
  const lines: string[] = [];
  for (const token of tokens.tokens) {
    const defaultValue = token.valuesByMode.get(token.defaultModeName);
    if (defaultValue === undefined) {
      continue;
    }
    appendTokenLines(lines, token.cssId, defaultValue, " /* " + buildCssComment(token) + " */");
  }
  if (lines.length === 0) {
    return ":root {\n}";
  }
  return `:root {\n${lines.join("\n")}\n}`;
}

function renderModeOverrideBlocks(tokens: TokenSet): readonly string[] {
  const blocks: string[] = [];
  for (const [slug, modes] of tokens.modesBySetSlug) {
    if (modes.length <= 1) {
      continue;
    }
    const defaultMode = modes[0]!;
    for (let i = 1; i < modes.length; i += 1) {
      const modeName = modes[i]!;
      const block = renderOverrideBlockForMode(tokens, slug, modeName, defaultMode);
      if (block) {
        blocks.push(block);
      }
    }
  }
  return blocks;
}

function renderOverrideBlockForMode(
  tokens: TokenSet,
  setSlug: string,
  modeName: string,
  defaultModeName: string,
): string | undefined {
  const lines: string[] = [];
  for (const token of tokens.tokens) {
    if (token.variableSetSlug !== setSlug) {
      continue;
    }
    const overrideValue = token.valuesByMode.get(modeName);
    if (overrideValue === undefined) {
      continue;
    }
    const defaultValue = token.valuesByMode.get(defaultModeName);
    if (defaultValue !== undefined && valuesEqual(overrideValue, defaultValue)) {
      // No point emitting the same value the default mode already
      // declared — the cascade would behave identically.
      continue;
    }
    appendTokenLines(lines, token.cssId, overrideValue, "");
  }
  if (lines.length === 0) {
    return undefined;
  }
  const selectorMode = cssQuotedAttributeValue(modeName);
  return `:root[data-${slugifyForCss(setSlug)}-mode=${selectorMode}] {\n${lines.join("\n")}\n}`;
}

function appendTokenLines(
  lines: string[],
  cssId: string,
  value: TokenValue,
  comment: string,
): void {
  if (value.kind === "typography") {
    expandTypographyLines(lines, cssId, value, comment);
    return;
  }
  lines.push(`  --${cssId}: ${renderCssValue(value)};${comment}`);
}

function expandTypographyLines(
  lines: string[],
  cssId: string,
  value: TypographyValue,
  comment: string,
): void {
  lines.push(`  --${cssId}-font-family: ${value.fontFamily};${comment}`);
  lines.push(`  --${cssId}-font-size: ${value.fontSize};`);
  if (value.fontWeight !== undefined) {
    lines.push(`  --${cssId}-font-weight: ${value.fontWeight};`);
  }
  if (value.lineHeight !== undefined) {
    lines.push(`  --${cssId}-line-height: ${value.lineHeight};`);
  }
  if (value.letterSpacing !== undefined) {
    lines.push(`  --${cssId}-letter-spacing: ${value.letterSpacing};`);
  }
}

function renderCssValue(value: TokenValue): string {
  switch (value.kind) {
    case "color":
      return value.css;
    case "number":
      return value.unit ? `${value.value}${value.unit}` : `${value.value}`;
    case "boolean":
      return value.value ? "1" : "0";
    case "string":
      return JSON.stringify(value.value);
    case "shadow":
      return value.css;
    case "raw-css":
      return value.css;
    case "typography":
      throw new Error("fig-to-tokens: renderCssValue must not be called for typography (use expandTypographyLines)");
  }
}

function valuesEqual(a: TokenValue, b: TokenValue): boolean {
  if (a.kind !== b.kind) {
    return false;
  }
  if (a.kind === "color" && b.kind === "color") {
    return a.css === b.css;
  }
  if (a.kind === "number" && b.kind === "number") {
    return a.value === b.value && a.unit === b.unit;
  }
  if (a.kind === "boolean" && b.kind === "boolean") {
    return a.value === b.value;
  }
  if (a.kind === "string" && b.kind === "string") {
    return a.value === b.value;
  }
  if (a.kind === "shadow" && b.kind === "shadow") {
    return a.css === b.css;
  }
  if (a.kind === "raw-css" && b.kind === "raw-css") {
    return a.css === b.css;
  }
  if (a.kind === "typography" && b.kind === "typography") {
    return (
      a.fontFamily === b.fontFamily &&
      a.fontSize === b.fontSize &&
      a.fontWeight === b.fontWeight &&
      a.lineHeight === b.lineHeight &&
      a.letterSpacing === b.letterSpacing
    );
  }
  return false;
}

function cssQuotedAttributeValue(input: string): string {
  // CSS attribute selector value: prefer double quotes; escape inner
  // double-quotes and backslashes per the CSS string-token grammar.
  const escaped = input.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

function buildCssComment(token: Token): string {
  const segments: string[] = [];
  if (token.source === "variable" && token.variableSetName) {
    segments.push(`${token.variableSetName}/${token.path.split("/").pop() ?? token.path}`);
  } else {
    segments.push(token.path);
  }
  return segments.join(" · ").replace(/\*\//g, "*\\/");
}
